on: push
name: deploy
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Execute python
        run: echo The username is ${{ inputs.SF_ACCOUNT }}
      - name: push python
        run: echo "This step will run finally"