# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Execute python
      run: echo The database is ${{ secrets.SF_DATABASE }}
    - uses: actions/checkout@v3
    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: executeScript
      run: |
          echo start script ... 
          ls -l
          sed -i "s/SF_ACCOUNT_DEV/"${{ secrets.SF_ACCOUNT }}"/" config.ini
          sed -i "s/SF_USER_DEV/"${{ secrets.SF_USER }}"/" config.ini
          sed -i "s/SF_PASS_DEV/"${{ secrets.SF_PASS }}"/" config.ini
          sed -i "s/SF_WAREHOUSE_DEV/"${{ secrets.SF_WAREHOUSE }}"/" config.ini
          sed -i "s/SF_DATABASE_DEV/"${{ secrets.SF_DATABASE }}"/" config.ini
          sed -i "s/SF_SCHEMA_DEV/"${{ secrets.SF_SCHEMA }}"/" config.ini
          cat config.ini
          echo End script

    - name: Test python code
      run: python main.py
    - name: Deploy script in bucket
      run: echo Storing in S3
